// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: piservice.proto

package piservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start    int32 `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Accuracy int32 `protobuf:"varint,2,opt,name=Accuracy,proto3" json:"Accuracy,omitempty"`
}

func (x *PiRequest) Reset() {
	*x = PiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiRequest) ProtoMessage() {}

func (x *PiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_piservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiRequest.ProtoReflect.Descriptor instead.
func (*PiRequest) Descriptor() ([]byte, []int) {
	return file_piservice_proto_rawDescGZIP(), []int{0}
}

func (x *PiRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PiRequest) GetAccuracy() int32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type PiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pi float64 `protobuf:"fixed64,1,opt,name=Pi,proto3" json:"Pi,omitempty"`
}

func (x *PiResponse) Reset() {
	*x = PiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiResponse) ProtoMessage() {}

func (x *PiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_piservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiResponse.ProtoReflect.Descriptor instead.
func (*PiResponse) Descriptor() ([]byte, []int) {
	return file_piservice_proto_rawDescGZIP(), []int{1}
}

func (x *PiResponse) GetPi() float64 {
	if x != nil {
		return x.Pi
	}
	return 0
}

var File_piservice_proto protoreflect.FileDescriptor

var file_piservice_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x3d, 0x0a, 0x09,
	0x50, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x22, 0x1c, 0x0a, 0x0a, 0x50,
	0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x50, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x50, 0x69, 0x32, 0x45, 0x0a, 0x06, 0x43, 0x61, 0x6c,
	0x63, 0x50, 0x69, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50,
	0x69, 0x12, 0x14, 0x2e, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_piservice_proto_rawDescOnce sync.Once
	file_piservice_proto_rawDescData = file_piservice_proto_rawDesc
)

func file_piservice_proto_rawDescGZIP() []byte {
	file_piservice_proto_rawDescOnce.Do(func() {
		file_piservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_piservice_proto_rawDescData)
	})
	return file_piservice_proto_rawDescData
}

var file_piservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_piservice_proto_goTypes = []interface{}{
	(*PiRequest)(nil),  // 0: piservice.PiRequest
	(*PiResponse)(nil), // 1: piservice.PiResponse
}
var file_piservice_proto_depIdxs = []int32{
	0, // 0: piservice.CalcPi.GeneratePi:input_type -> piservice.PiRequest
	1, // 1: piservice.CalcPi.GeneratePi:output_type -> piservice.PiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_piservice_proto_init() }
func file_piservice_proto_init() {
	if File_piservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_piservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_piservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_piservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_piservice_proto_goTypes,
		DependencyIndexes: file_piservice_proto_depIdxs,
		MessageInfos:      file_piservice_proto_msgTypes,
	}.Build()
	File_piservice_proto = out.File
	file_piservice_proto_rawDesc = nil
	file_piservice_proto_goTypes = nil
	file_piservice_proto_depIdxs = nil
}
