// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: piservice.proto

package piservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalcPiClient is the client API for CalcPi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcPiClient interface {
	GeneratePi(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error)
}

type calcPiClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcPiClient(cc grpc.ClientConnInterface) CalcPiClient {
	return &calcPiClient{cc}
}

func (c *calcPiClient) GeneratePi(ctx context.Context, in *PiRequest, opts ...grpc.CallOption) (*PiResponse, error) {
	out := new(PiResponse)
	err := c.cc.Invoke(ctx, "/piservice.CalcPi/GeneratePi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcPiServer is the server API for CalcPi service.
// All implementations must embed UnimplementedCalcPiServer
// for forward compatibility
type CalcPiServer interface {
	GeneratePi(context.Context, *PiRequest) (*PiResponse, error)
	mustEmbedUnimplementedCalcPiServer()
}

// UnimplementedCalcPiServer must be embedded to have forward compatible implementations.
type UnimplementedCalcPiServer struct {
}

func (UnimplementedCalcPiServer) GeneratePi(context.Context, *PiRequest) (*PiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePi not implemented")
}
func (UnimplementedCalcPiServer) mustEmbedUnimplementedCalcPiServer() {}

// UnsafeCalcPiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcPiServer will
// result in compilation errors.
type UnsafeCalcPiServer interface {
	mustEmbedUnimplementedCalcPiServer()
}

func RegisterCalcPiServer(s grpc.ServiceRegistrar, srv CalcPiServer) {
	s.RegisterService(&CalcPi_ServiceDesc, srv)
}

func _CalcPi_GeneratePi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcPiServer).GeneratePi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/piservice.CalcPi/GeneratePi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcPiServer).GeneratePi(ctx, req.(*PiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalcPi_ServiceDesc is the grpc.ServiceDesc for CalcPi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalcPi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piservice.CalcPi",
	HandlerType: (*CalcPiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePi",
			Handler:    _CalcPi_GeneratePi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "piservice.proto",
}
